name: Deploy website

on:
 push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 9
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Netlify
        run: pnpm install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run generate

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir .output/public \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod
